name = "潇洒哥和黑大帅"
# avatar = "images/profile.png" # Avatar image. Default to "images/profile.webp".
avatar = "images/logo.jpg"
bio = "Go基础系列、从0开发微服务（后续）、杂七杂八。"
# company = "Null"
# location = "Earth"
# about = "https://domain.tld" # The external about page. The internal about page will be used if not set.
