name = "潇洒哥老苗"
# avatar = "images/profile.png" # Avatar image. Default to "images/profile.webp".
avatar = "images/laomiao.jpg?v=0.1"
bio = "Gopher、英语、思考、持续学习。"
# company = "Null"
location = ""
# about = "https://domain.tld" # The external about page. The internal about page will be used if not set.
