[[main]]
  name = "在线工具"
  identifier = "dropdown"
[[main]]
  parent = "dropdown"
  name = "JSON转GO"
  url = "/tools/json2go"
[[main]]
  parent = "dropdown"
  name = "SQL转GORM"
  url = "/tools/sql2gorm"
