[[main]]
  name = "免费资源"
  url = "/posts/books/toc/"
[[main]]
  name = "在线工具"
  identifier = "dropdown"
[[main]]
  parent = "dropdown"
  name = "JSON转GO"
  url = "/tools/json2go"
[[main]]
  parent = "dropdown"
  name = "SQL转GORM"
  url = "/tools/sql2gorm"
[[main]]
  parent = "dropdown"
  name = "SQL转go-zero"
  url = "/tools/sql2gozero"
[[main]]
  parent = "dropdown"
  name = "SQL转entgo"
  url = "/tools/sql2ent"