# mainSections = ["post", "posts"] # Default to ["posts"].

# titleSeparator = "|" # Title separator. Default to "-".

# description = "An extreme fast, responsive and feature-rich blog theme for Hugo"
# images = ["site-feature-image.jpg"]

# logo = "images/logo.png" # Logo image. Default to "images/logo.webp".
logo = "images/logo.jpg"
brand = "PrintLove"
# menusPosition = "left" # Menus position: right(default), left or center.

palette = "blue-gray" # Default palette. Optional.
# palettes = ["blue", "blue gray", "brown"] # Available palettes. Default to ALL.
# palettes = [] # Disable palette switcher.

# color = "dark" # light, dark or dynamic. Default to dynamic.

# fullWidth = true # Full width.
fixedHeader = false # Turn on/off fixed header.

# dateFormat = "Jan 2, 2006"

# Google Adsense
googleAdsense = ""

# math = true # Enable math globally.
# toc = false # Disable TOC globally.
breadcrumb = false # Disable breadcrumb

poweredBy = true # Whether to show powered by.

# featuredPostCount = 10 # The number of featured posts shown in sidebar.
# recentPostCount = 10 # The number of recent posts shown in sidebar.
# relatedPostCount = 10 # The number of related posts.
# categoryCount = 10 # The number of categories shown in sidebar.
tagCount = 30 # The number of tags shown in sidebar.
# seriesCount = 10 # The number of series shown in sidebar.

# Custom CSS and JS
customCSS = [
  "/codemirror/lib/codemirror.css",
  "/codemirror/addon/scroll/simplescrollbars.css",
  "/codemirror/theme/monokai.css"
]
customJS = [
  "/codemirror/lib/codemirror.js",
  "/codemirror/mode/sql/sql.js",
  "/codemirror/mode/go/go.js",
  "/codemirror/mode/javascript/javascript.js",
  "/codemirror/mode/yaml/yaml.js",
  "/codemirror/mode/xml/xml.js",
  "/codemirror/addon/scroll/simplescrollbars.js"
]

# tocWordCount = 280 # TOC is displayed only if the post's word count exceeds this value.

[archive]
  paginate = 8 # Archive pagination. Default to 100.
  # dateFormat = "01-02" # Archive date format. Default to "Jan 2".

[analytics]
  baidu = "4bddc7ae6f2203e19017f349bdcc79c2" # Baidu Analytics

# Site verification
[siteVerification]
  google = "9Qpc8B088mjrQPtVx38X3LVnltbTV3m-Y7tz90nQ5qw"
  bing = "F76BCD611A8614917D62A8E5CF6326A9"
  baidu = "code-NTfzacnFYd"
  baiduUnion = "" # Baidu Union
  so = ""
  sogou = ""
  shenma = ""

[creativeCommons]
  by = true # Credit must be given to you, the creator.
  nc = true # Only noncommercial use of your work is permitted.
  nd = true # No derivatives or adaptations of your work are permitted.
  sa = true # Adaptations must be shared under the same terms.

[utterances]
  repo = "miaogaolin/printlove-comment"
  #issueTerm = "pathname" # pathname, url, title, og:title
  #label = "comment"
  theme = "auto" # github-light, github-dark, preferred-color-scheme, github-dark-orange, icy-dark, dark-blue, photon-dark.

[search]
  paginate = 5 # Pagination. Default to 10.
  # resultContentWordCount = 240 # The maximum word count of result content for displaying.
  # Fuse.js options. See https://fusejs.io/api/options.html.
  [search.fuse]
    # ignoreLocation = true
    # location = 0
    # isCaseSensitive = false
    # minMatchCharLength = 1
    threshold = 0.1
    # distance = 100
    # useExtendedSearch = true

#[reward]
  #alipay = "images/reward/alipay.png"
  #wechat = "images/reward/wechat.png"

[share]
  # addThis = "ra-60bcc43f59f2d04f" # AddThis pubid.

# [fontSize] # Comment or remove this settings to disable font size switcher.
#   extraSmall = ".8rem"
#   small = ".9rem"
#   large = "1.1rem"
#   extraLarge = "1.2rem"
