email = "2825873215@qq.com"
# facebook = "yourfacebookusername"
github = "miaogaolin"
# gitlab = "yourgitlabusername"
# linkedin = "yourlinkedinusername"
# stackoverflow = "yourstackoverflowuserid"
twitter = "laomiao_"
# weibo = "yourweibousername"
zhihu = "fan-zhong-li-luo-xie"
# instagram = "yourinstagramusername"
# quora = "yourquorausername"
# tumblr = "yourtumblrusername"
# reddit = "yourredditusername"
# telegram = "yourtelegramusername"
qq = "2825873215"
# dockerhub = "yourdockerhubusername"
# bitbucket = "yourbitbucketworkspaceid"
# medium = "yourmediumusername" # Medium username or custom domain(e.g. https://custom.domain.tld).
# lastfm = "yourlastfmusername"
